import { Cascadia_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar/Navbar";
import SmoothScroll from "@/components/animations/Lenis/SmoothScroll";
import Footer from "@/components/Shared/Footer/Footer";

const Cascadia_Code_Font = Cascadia_Code({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${Cascadia_Code_Font.className} h-full antialiased`}
    >
      <body
        className="bg-[#020817] text-white min-h-screen"
        style={{
          backgroundColor: "#020817",
          backgroundImage:
            "radial-gradient(ellipse 100% 40% at 50% 0%, rgba(14,30,70,0.5) 0%, transparent 70%)",
        }}
      >
        <Navbar />
        <SmoothScroll>
          <main className="antialiased">
            {children}
          </main>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}